export const CHANGE_COUNTRY_SUCCESS = "CHANGE_COUNTRY_SUCCESS";
export const CHANGE_COUNTRY_FAILURE = "CHANGE_COUNTRY_FAILURE";

export const GET_TOP_HEADLINES_SUCCESS = "GET_TOP_HEADLINES_SUCCESS";
export const GET_TOP_HEADLINES_FAILURE = "GET_TOP_HEADLINES_FAILURE";

export const GET_SEARCH_RESULTS_SUCCESS = "GET_SEARCH_RESULTS_SUCCESS";
export const GET_SEARCH_RESULTS_FAILURE = "GET_SEARCH_RESULTS_FAILURE";

export const GET_NEWS_BY_CATEGORY_SUCCESS = "GET_NEWS_BY_CATEGORY_SUCCESS";
export const GET_NEWS_BY_CATEGORY_FAILURE = "GET_NEWS_BY_CATEGORY_FAILURE";

export const SET_LOADING = "SET_LOADING";

export const SET_COUNTRY = "SET_COUNTRY";

export const TOGGLE_THEME = "TOGGLE_THEME";
export const TOGGLE_THEME_SUCCESS = "TOGGLE_THEME_SUCCESS";
export const TOGGLE_THEME_FAILURE = "TOGGLE_THEME_FAILURE";
